### ISSUE TITLE
Is this production-ready?

### ISSUE THREAD

**Issue by gautvm** [tsar-boomba/network-tables-rs#1]
Hi, first of all, thanks for creating this. It's nice to see an actively-maintained NetworkTables rust client.

I was wondering if this is stable, and in a state to be used in production. I'm planning to use this in a project, but it seems quite new.

**Comment by tsar-boomba** [comment]
After we test the newest release on [my team's dashboard](https://github.com/Yeti-Robotics/genius-dashboard) tomorrow, I'll have your answer. This latest release fixes a bug in the code that is likely the culprit of issues we've had with our dashboard.

**Comment by gautvm** [comment]
Great, thanks.

**Comment by tsar-boomba** [comment]
After doing more testing and bug fixes, I would say this is ready for production.

**Comment by gautvm** [comment]
Awesome, thanks a lot!
